config/routes.rb
Demo::Application.routes.draw do

  resources :vehicles

  root  :to => 'vehicles#index' # target root
  get   'sign_in' => 'auth#sign_in'
  get   'sign_up' => 'auth#sign_up'
  get   'sign_out' => 'auth#sign_out'
  post  'sign_in' => 'auth#login'
  post  'sign_up' => 'auth#register'
  get   'activate' => 'auth#activate'
  post  'people/create' => 'people#create', :as => 'complete_registration'
  get   'people/new' => 'people#new', :as => 'new_profile'

end

app/models/person.rb
class Person < ActiveRecord::Base
  belongs_to :user
  attr_accessible :first_name, :last_name, :city, :province, :address, :phone_number, :postal_code
  validates :phone_number, numericality: {only_integer: true, message: "Should contain numbers only"},
            length: { is: 10, message: "Should contain 10 numbers"}
  validates :postal_code, format: {with: /^([A-Za-z]\d){3}$/, message: "invalid postal code."},
      length: { is: 6}
  validates :first_name, :last_name, :address, :province, :postal_code, :city, :phone_number, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation
  attr_accessor :password
  before_save :encrypt_password

  validates :password, confirmation: true
  validates :password, :email, presence: true, :on => :create
  validates :email, uniqueness: true

  has_one :person, dependent: :destroy
  has_many :vehicles, dependent: :destroy

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt) && user.activation_token == nil
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  belongs_to :user
  attr_accessible :license_plate, :colour, :make, :model, :year

  validates :license_plate, :make, presence: true
  validates :year, numericality: { only_integers: true }, length: { is: 4, message: "invalid year" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
  end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  before_filter :check_session, only: [:sign_in, :sign_up, :register, :activate] # check if a user has already logged in

  def sign_in
    @user = User.new
  end

  def sign_up
    @user = User.new
  end

  def login
    email = params[:user][:email]
    password = params[:user][:password]

    user = User.authenticate(email, password)

    if user
      session[:user_id] = user.id
      flash[:notice] = 'Welcome!'
      redirect_to :root
    else
      flash[:notice] = 'Email or password do not match or records'
      render :action => 'sign_in'
    end
  end

  def register
    @user = User.new(params[:user])

    if @user.valid?
      @user.activation_token = SecureRandom.urlsafe_base64
      @user.activation_expires_after = 24.hours.from_now
      @user.save
      UserMailer.welcome_email(@user).deliver
      flash[:notice] = 'Thank you for registration! Please check your mail-box for confirmation.'
      redirect_to sign_in_url
    else
      render :action => 'sign_up'
    end
  end

  def activate
    token = params.first[0]
    user = User.find_by_activation_token(token)
    if user.nil?
      flash[:error] = 'Wrong activation key. Please check your mail box.'
      redirect_to :root
      return
    end
    if user.activation_expires_after < DateTime.now
      flash[:notice] = 'Your activation has expired. Please request a new account activation.'
      redirect_to sign_in_url
    else
      user.activation_token = nil
      user.activation_expires_after = nil
      user.save

      session[:user_id] = user.id
      flash[:notice] = 'Your account was successfully activated. Please complete registration process.'
      redirect_to new_profile_url
    end
  end

  def sign_out
    session[:user_id] = nil
    flash[:notice] = "You have been signed out."
    redirect_to sign_in_url
  end

  private

  def check_session
    if current_user
      redirect_to root_url
    end
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def new
    if current_user && current_user.person == nil
      @person = Person.new
    else
      redirect_to :sign_in
    end
  end

  def create
    @person = Person.new(params[:person])

    if @person.valid?
      current_user.person = @person
      current_user.save
      flash[:notice] = "Thank you for completing your registration!"
      redirect_to :root
    else
      render :action => 'new'
    end
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_filter :require_login
  before_filter :require_info
  before_filter :require_auth, only: [:show, :destroy, :edit, :update]

  def index
    @vehicles = current_user.vehicles
  end

  def new
    @vehicle = Vehicle.new
  end
  def create
    @vehicle = Vehicle.new(params[:vehicle])

    if @vehicle.valid?
      @vehicle.user = current_user
      @vehicle.save
      flash[:notice] = 'Vehicle was successfully saved!'
      redirect_to vehicles_url
    else
      render :action => 'new'
    end
  end
  def show

  end
  def destroy

  end

  private

  def require_login
    if current_user.nil?
      redirect_to sign_in_url
    end
  end

  def require_info
    if current_user.person.nil?
      flash[:notice] = 'Please complete your registration'
      redirect_to new_profile_url
    end
  end

  def require_auth
    id = params[:id]
    vehicle = Vehicle.find_by_id(id)

    if vehicle.nil? || vehicle.user != current_user
      flash[:error] = "Vehicle not found"
      redirect_to vehicles_url
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_field_error(model, field)
    s = ""

    if !model.errors[field].empty?
      s =
          <<-EOHTML
            <div class="error_message">
            #{model.errors[field][0]}
            </div>
          EOHTML
    end

    s.html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<p>
  <%= link_to 'Home', root_path %>
  <% if current_user %>
    Logged in as <%= current_user.email %>.
  <%= link_to "Sign Out", sign_out_path %>
  <% else %>
    <%= link_to "Sign up", sign_up_path %> or
    <%= link_to "Sign In", sign_in_path %>
  <% end %>
</p>

<p>
  <% flash.each do |name, msg| %>
  <%= content_tag :div, msg %>
  <% end %>
</p>
<%= yield %>

</body>
</html>

app/views/people/new.html.erb
<div class="container">
  <%= form_for @person, :as => :person, :url => complete_registration_path(@person), :html => { :class => 'form-signin'}, :method => :post do |p| %>
      <h2 class="form-signin-heading">Personal Information</h2>
      <%= p.text_field :first_name, :class => 'form-control', :placeholder => 'first name' %>
      <%= show_field_error(@person, :first_name) %>
      <%= p.text_field :last_name, :class => 'form-control', :placeholder => 'last name' %>
      <%= show_field_error(@person, :last_name) %>
      <%= p.text_field :address, :class => 'form-control', :placeholder => 'address' %>
      <%= show_field_error(@person, :address) %>
      <%= p.text_field :city, :class => 'form-control', :placeholder => 'city' %>
      <%= show_field_error(@person, :city) %>
      <%= p.select :province, options_for_select([['Ontario', 'Ontario'],['Quebec','Quebec'],['Alberta', 'Alberta']]),{}, {:class => 'form-control'} %>
      <%= show_field_error(@person, :province) %>
      <%= p.text_field :postal_code, :class => 'form-control', :placeholder => 'postal code' %>
      <%= show_field_error(@person, :postal_code) %>
      <%= p.text_field :phone_number, :class => 'form-control', :placeholder => 'phone_number' %>
      <%= show_field_error(@person, :phone_number) %>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Save</button>
  <% end %>
</div>

app/views/vehicles/index.html.erb
  <% if @vehicles.empty? %>
  No vehicles to display
  <% else %>
      <table class="table table-striped">
        <thead>
        <th>License Plate</th>
        <th>Colour</th>
        <th>Make</th>
        <th>Model</th>
        <th>Year</th>
        </thead>
        <tbody>
          <% @vehicles.each do |v| %>
            <tr>
              <td><%= v.license_plate %></td>
              <td><%= v.colour %></td>
              <td><%= v.make %></td>
              <td><%= v.model %></td>
              <td><%= v.year %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
  <% end %>


<p>
  <%= link_to 'Add Vehicle', new_vehicle_path %>
</p>

app/views/vehicles/new.html.erb
<div class="container">
  <%= form_for @vehicle, :as => :vehicle, :url => vehicles_path(@vehicle), :html => { :class => 'form-signin'}, :method => :post do |p| %>
      <h2 class="form-signin-heading">Vehicle Registration</h2>
      <%= p.text_field :license_plate, :class => 'form-control', :placeholder => 'plate number' %>
      <%= show_field_error(@vehicle, :license_plate) %>
      <%= p.text_field :colour, :class => 'form-control', :placeholder => 'colour' %>
      <%= show_field_error(@vehicle, :colour) %>
      <%= p.text_field :make, :class => 'form-control', :placeholder => 'make' %>
      <%= show_field_error(@vehicle, :make) %>
      <%= p.text_field :model, :class => 'form-control', :placeholder => 'model' %>
      <%= show_field_error(@vehicle, :model) %>
      <%= p.text_field :year, :class => 'form-control', :placeholder => 'year' %>
      <%= show_field_error(@vehicle, :year) %>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Save</button>
  <% end %>
</div>